### PR TITLE
[DEV] adding `plink --bfile` and `nf-core/plink/vcf`

### PR DESCRIPTION
**Pull request by Mxrcon**
Hey :wave:, I'm adding plink modules as we discussed on our last meeting. This should be a nice first step for the base workflow development!

Observations about the module: 
- I tried to add as many optional outputs plink would have, i also added the dups optional input that is required for the `--exclude` param to exclude specific variants.

- The current state of args should be able to parse any kind of optional run type you select for plink, i tried some of them and they seem to be working :raised_hands:.

- The module follow the nf-core ruling, hope that after some testing we can add it as a module as i already started the foundations at my [fork of nf-core modules](https://github.com/mxrcon/modules/tree/dev-plink-bfile)

I'm waiting for review on this, your thoughts would be very helpful.

Kindly, Davi

### CODE REVIEW

**Comment by abhi18av** [comment]
This is on my Todo list for today Davi - apologies for the delay in circling back on this.

**Review by abhi18av — APPROVED** [review]
Davi, to me this looks good to merge 👏 

The overall form of the pipeline/modules will reveal itself once we have experience with it so in the meantime we are free to experiment/iterate on this faster.

**Comment by abhi18av** [comment]
Whoops, there's a merge conflict with the upstream `dev` and modules structure - would you mind looking into this please?

**Comment by Mxrcon** [comment]
@abhi18av solved using the dev branch changes, if this thrown any error we can regenerate the `modules.config` again with nf-core tools

**Comment by abhi18av** [comment]
Oki doki - sounds good :)

**Pull request merged**
